[build]
  command = "npm ci --include=dev && npm run build:client"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
